### ISSUE TITLE
Having this project under opencensus-beam umbrella

### ISSUE THREAD

**Issue by deadtrickster** [opencensus-beam/tracelog#1]
Hi, we have this opencensus-beam org where collect integrations. Would be cool to have tracelog here too. What you think?

https://github.com/opencensus-beam

**Comment by ferd** [comment]
Ah sorry for missing this. I forgot to subscribe to my own repo and never saw the notification for it.

I'd be open to it, but I'd like to get some feedback from people who deployed it to prod first. This is a bit experimental and it'd be good not to advertise experimental stuff as prod-ready

**Comment by hauleth** [comment]
@ferd not all projects in opencensus-beam org are currently deployed and stated as production ready (notably InfluxDB and Telemetry integrations are still to be released on Hex). So I wouldn't see a problem there.

**Comment by ferd** [comment]
I'm fine adding the project there. Curious to see what it would look like if I wanted to add support for more than one distributed tracing framework though (i.e. choose your own handler for each framework). Would that cause issues?

**Comment by deadtrickster** [comment]
I would say as long as it supports opencensus we are fine. Shall I add you to the org?

**Comment by ferd** [comment]
I'm good with that yeah

**Comment by ferd** [comment]
Done, ownership transfered so everyone who consults old links gets redirected here as well
